FROM postgres:14.8

# https://www.postgresql.org/docs/current/libpq-envars.html
# Set default PostgreSQL superuser login
ENV POSTGRES_USER=postgres

# Set the PostgreSQL superuser password
ENV POSTGRES_PASSWORD=password

# Set the name of the default container that is created on first start
ENV POSTGRES_DB=postgres

EXPOSE 5432