server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape application logs written to files
  - job_name: retrospect-server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: retrospect-server
          environment: development
          service: retrospect-server
          __path__: /app/logs/*.log

    # Parse JSON logs from Pino
    pipeline_stages:
      - json:
          expressions:
            level: level
            time: time
            msg: msg
            service: service
            requestId: requestId
            userId: userId
            method: method
            url: url
            statusCode: statusCode
            responseTime: responseTime

      # Convert Pino log levels to standard levels
      - template:
          source: level_name
          template: '{{ if eq .level "10" }}trace{{ else if eq .level "20" }}debug{{ else if eq .level "30" }}info{{ else if eq .level "40" }}warn{{ else if eq .level "50" }}error{{ else if eq .level "60" }}fatal{{ else }}unknown{{ end }}'

      # Set timestamp from log entry
      - timestamp:
          source: time
          format: RFC3339

      # Add labels for filtering
      - labels:
          level_name:
          service:
          method:
          statusCode:
